spring:
    profiles: prod
    thymeleaf:
      prefix: classpath:/templates/
      mode: LEGACYHTML5
    datasource:
      url: jdbc:mysql://localhost:3306/weixin?useUnicode=true&amp;characterEncoding=utf-8
      username: root
      password: zfj1121
      driver-class-name: com.mysql.jdbc.Driver


    jpa:
      properties:
        hibernate:
          hbm2ddl.auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true

#    mail:
#      host: smtp.qq.com
#      username: 1329605202@qq.com
#      default-encoding: UTF-8
#      password: uzrpkbouzjhogcec
#      port: 25
#      protocol: smtp
#
##    配置redis
#    redis:
#      database: 0
#      host: localhost
##      password: zfj1121
#      port: 6379
#      pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#      # 连接超时时间（毫秒）
#      timeout: 0
#
#
#
#mail:
#  fromMail:
#    addr: ${spring.mail.username}

server:
    port: 80
    context-path: /mg



